import { describe, expect, it } from 'bun:test'
import { checkForAutoClose, extractPackageNamesFromPRBody } from '../src/utils/helpers'
import { Logger } from '../src/utils/logger'

describe('Auto-Close Regression Tests', () => {
  const mockLogger = new Logger(false) // Quiet logger for tests

  it('should auto-close PR with dynamic version (*)', async () => {
    const prBody = `This PR contains the following updates:

system

| Package                                       | Change        | Type     | File                                                                                                  |
| --------------------------------------------- | ------------- | -------- | ----------------------------------------------------------------------------------------------------- |
| [python.org](https://pkgx.com/pkg/python.org) | * → 3.13.5 | 🔴 major | [pkgx.yml](https://github.com/stacksjs/launchpad/blob/main/packages/launchpad/test/fixtures/pkgx.yml) |

---

This PR was generated by Buddy 🤖`

    const pr = {
      number: 48,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(true)
  })

  it('should auto-close PR with dynamic version (latest)', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [react](https://npmjs.com/package/react) | latest → 18.2.0 | 🔴 major |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 49,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(true)
  })

  it('should NOT auto-close PR with normal versions', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [typescript](https://npmjs.com/package/typescript) | 5.0.0 → 5.1.0 | 🟡 minor |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 50,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(false)
  })

  it('should NOT auto-close when respectLatest is false', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [python.org](https://pkgx.com/pkg/python.org) | * → 3.13.5 | 🔴 major |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 51,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: false,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(false)
  })

  it('should extract package names correctly from PR body', () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [python.org](https://pkgx.com/pkg/python.org) | * → 3.13.5 | 🔴 major |
| [react](https://npmjs.com/package/react) | latest → 18.2.0 | 🔴 major |

This PR was generated by Buddy 🤖`

    const packages = extractPackageNamesFromPRBody(prBody)
    expect(packages).toEqual(['python.org', 'react'])
  })

  it('should handle PRs without table format', () => {
    const prBody = `This PR updates some packages:

- python.org: * → 3.13.5
- react: latest → 18.2.0

This PR was generated by Buddy 🤖`

    const packages = extractPackageNamesFromPRBody(prBody)
    expect(packages).toEqual([]) // Should not find packages in non-table format
  })

  it('should auto-close PR with dynamic version with backticks (*)', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [python.org](https://pkgx.com/pkg/python.org) | \`*\` → \`3.13.5\` | 🔴 major |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 52,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(true)
  })

  it('should auto-close PR with dynamic version with backticks (latest)', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [react](https://npmjs.com/package/react) | \`latest\` → \`18.2.0\` | 🔴 major |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 53,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(true)
  })

  it('should NOT auto-close PR with normal versions with backticks', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [react](https://npmjs.com/package/react) | \`^18.2.0\` → \`^18.3.0\` | 🟡 minor |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 55,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(false)
  })

  it('should generate correct comment when auto-closing PR', () => {
    const packageNames = ['python.org', 'react']
    const comment = `🤖 **Auto-closed by Buddy Bot**

This PR was automatically closed because it contains updates for packages with dynamic version indicators (like \`*\`, \`latest\`, etc.) that are now filtered out by the \`respectLatest\` configuration.

**Affected packages:** ${packageNames.join(', ')}

The \`respectLatest\` setting (default: \`true\`) prevents updates to packages that use dynamic version indicators, as these are typically meant to always use the latest version and shouldn't be pinned to specific versions.

If you need to update these packages to specific versions, you can:
1. Set \`respectLatest: false\` in your \`buddy-bot.config.ts\`
2. Or manually update the dependency files to use specific versions instead of dynamic indicators

This helps maintain the intended behavior of dynamic version indicators while preventing unwanted updates.`

    expect(comment).toContain('🤖 **Auto-closed by Buddy Bot**')
    expect(comment).toContain('python.org, react')
    expect(comment).toContain('respectLatest')
    expect(comment).toContain('buddy-bot.config.ts')
  })
})
