import { describe, expect, it } from 'bun:test'
import { checkForAutoClose, extractPackageNamesFromPRBody } from '../src/utils/helpers'
import { Logger } from '../src/utils/logger'

describe('Auto-Close Regression Tests', () => {
  const mockLogger = new Logger(false) // Quiet logger for tests

  it('should auto-close PR with dynamic version (*)', async () => {
    const prBody = `This PR contains the following updates:

system

| Package                                       | Change        | Type     | File                                                                                                  |
| --------------------------------------------- | ------------- | -------- | ----------------------------------------------------------------------------------------------------- |
| [python.org](https://pkgx.com/pkg/python.org) | * → 3.13.5 | 🔴 major | [pkgx.yml](https://github.com/stacksjs/launchpad/blob/main/packages/launchpad/test/fixtures/pkgx.yml) |

---

This PR was generated by Buddy 🤖`

    const pr = {
      number: 48,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(true)
  })

  it('should auto-close PR with dynamic version (latest)', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [react](https://npmjs.com/package/react) | latest → 18.2.0 | 🔴 major |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 49,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(true)
  })

  it('should NOT auto-close PR with normal versions', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [typescript](https://npmjs.com/package/typescript) | 5.0.0 → 5.1.0 | 🟡 minor |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 50,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(false)
  })

  it('should NOT auto-close when respectLatest is false', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [python.org](https://pkgx.com/pkg/python.org) | * → 3.13.5 | 🔴 major |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 51,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: false,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(false)
  })

  it('should extract package names correctly from PR body', () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [python.org](https://pkgx.com/pkg/python.org) | * → 3.13.5 | 🔴 major |
| [react](https://npmjs.com/package/react) | latest → 18.2.0 | 🔴 major |

This PR was generated by Buddy 🤖`

    const packages = extractPackageNamesFromPRBody(prBody)
    expect(packages).toEqual(['python.org', 'react'])
  })

  it('should handle PRs without table format', () => {
    const prBody = `This PR updates some packages:

- python.org: * → 3.13.5
- react: latest → 18.2.0

This PR was generated by Buddy 🤖`

    const packages = extractPackageNamesFromPRBody(prBody)
    expect(packages).toEqual([]) // Should not find packages in non-table format
  })

  it('should auto-close PR with dynamic version with backticks (*)', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [python.org](https://pkgx.com/pkg/python.org) | \`*\` → \`3.13.5\` | 🔴 major |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 52,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(true)
  })

  it('should auto-close PR with dynamic version with backticks (latest)', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [react](https://npmjs.com/package/react) | \`latest\` → \`18.2.0\` | 🔴 major |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 53,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(true)
  })

  it('should NOT auto-close PR with normal versions with backticks', async () => {
    const prBody = `This PR contains the following updates:

| Package | Change | Type |
| ------- | ------ | ---- |
| [typescript](https://npmjs.com/package/typescript) | \`5.0.0\` → \`5.1.0\` | 🟡 minor |

This PR was generated by Buddy 🤖`

    const pr = {
      number: 54,
      body: prBody,
    }

    const config = {
      packages: {
        respectLatest: true,
      },
    }

    const result = await checkForAutoClose(pr, config, mockLogger)
    expect(result).toBe(false)
  })
})
