import type { PackageUpdate, PullRequest } from '../src/types'
import { describe, expect, it } from 'bun:test'
import { checkForAutoClose, extractPackageNamesFromPRBody } from '../src/utils/helpers'
import { Logger } from '../src/utils/logger'

/**
 * Tests for PR duplicate prevention and auto-close regression fixes.
 *
 * These tests cover the root causes of the "PRs created over and over" bug:
 * 1. Arrow format mismatch: PR bodies use both `->` (ASCII) and `→` (Unicode)
 * 2. Partial extraction leading to false "satisfied" closures
 * 3. Overly broad PR filters catching non-buddy-bot PRs
 * 4. False positives on "main" in PR body configuration text
 */

const mockLogger = new Logger(false)

// Realistic PR body from ts-mocker with both npm (ASCII ->) and system deps (Unicode →)
const MIXED_PR_BODY = `This PR contains the following updates:

## Package Updates Summary

| Type | Count |
|------|-------|
| 📦 NPM Packages | 1 |
| 🔧 System Dependencies | 1 |
| **Total** | **2** |

## 📦 npm Dependencies

![npm](https://img.shields.io/badge/npm-CB3837?style=flat&logo=npm&logoColor=white)

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@types/bun](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bun) ([source](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/bun)) | [\`1.3.10\` -> \`1.3.11\`](https://renovatebot.com/diffs/npm/%40types%2Fbun/1.3.10/1.3.11) | [![age](https://developer.mend.io/api/mc/badges/age/npm/%40types%2Fbun/1.3.11?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/%40types%2Fbun/1.3.11?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/%40types%2Fbun/1.3.10/1.3.11?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/%40types%2Fbun/1.3.10/1.3.11?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

## 🔧 System Dependencies

![system](https://img.shields.io/badge/system-4CAF50?style=flat&logo=linux&logoColor=white)

| Package | Change | Type | File |
|---|---|---|---|
| [bun.com](https://bun.sh) | \`^1.3.1\` → \`^1.3.4\` | 🟢 patch | [\`deps.yaml\`](https://github.com/stacksjs/ts-mocker/blob/main/deps.yaml) |

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR was generated by [Buddy](https://github.com/stacksjs/buddy-bot) 🤖`

const GITHUB_ACTIONS_PR_BODY = `This PR contains the following updates:

## Package Updates Summary

| Type | Count |
|------|-------|
| 🚀 GitHub Actions | 3 |
| **Total** | **3** |

## 🚀 GitHub Actions

![github-actions](https://img.shields.io/badge/GitHub%20Actions-2088FF?style=flat&logo=github-actions&logoColor=white)

*3 actions will be updated*

| Action | Change | Type | Files |
|---|---|---|---|
| [oven-sh/setup-bun](https://github.com/oven-sh/setup-bun) | \`v2.1.2\` → \`v2.2.0\` | 🟡 minor | [\`ci.yml\`](https://github.com/stacksjs/ts-mocker/blob/main/.github/workflows/ci.yml) |
| [actions/checkout](https://github.com/actions/checkout) | \`v4.2.1\` → \`v4.2.2\` | 🟢 patch | [\`ci.yml\`](https://github.com/stacksjs/ts-mocker/blob/main/.github/workflows/ci.yml) |
| [codecov/codecov-action](https://github.com/codecov/codecov-action) | \`v4.5.0\` → \`v5.0.0\` | 🔴 major | [\`ci.yml\`](https://github.com/stacksjs/ts-mocker/blob/main/.github/workflows/ci.yml) |

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined).

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR was generated by [Buddy](https://github.com/stacksjs/buddy-bot) 🤖`

const NPM_ONLY_PR_BODY = `This PR contains the following updates:

## Package Updates Summary

| Type | Count |
|------|-------|
| 📦 NPM Packages | 2 |
| **Total** | **2** |

## 📦 npm Dependencies

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [typescript](https://www.typescriptlang.org/) ([source](https://github.com/microsoft/TypeScript)) | [\`^5.8.2\` -> \`^5.8.3\`](https://renovatebot.com/diffs/npm/typescript/5.8.2/5.8.3) | badge | badge | badge | badge |
| [eslint](https://eslint.org/) ([source](https://github.com/eslint/eslint)) | [\`^9.0.0\` -> \`^9.1.0\`](https://renovatebot.com/diffs/npm/eslint/9.0.0/9.1.0) | badge | badge | badge | badge |

---

This PR was generated by [Buddy](https://github.com/stacksjs/buddy-bot) 🤖`

// Helper to create a minimal Buddy instance for testing private methods
// We access the private methods via the prototype to test them directly
function createTestBuddy() {
  // eslint-disable-next-line ts/no-require-imports
  const { Buddy } = require('../src/buddy')
  return new Buddy({
    repository: { provider: 'github', owner: 'test', name: 'test' },
    packages: {},
  }, '/tmp/test')
}

describe('PR Duplicate Prevention', () => {
  describe('extractPackageUpdatesFromPRBody (via Buddy)', () => {
    const buddy = createTestBuddy()
    // Access private method for testing
    const extract = (body: string) => (buddy as any).extractPackageUpdatesFromPRBody(body)

    it('should extract npm packages with ASCII arrow (->)', () => {
      const updates = extract(NPM_ONLY_PR_BODY)
      expect(updates.length).toBe(2)
      expect(updates[0].name).toBe('typescript')
      expect(updates[0].currentVersion).toBe('5.8.2')
      expect(updates[0].newVersion).toBe('5.8.3')
      expect(updates[1].name).toBe('eslint')
      expect(updates[1].currentVersion).toBe('9.0.0')
      expect(updates[1].newVersion).toBe('9.1.0')
    })

    it('should extract system deps with Unicode arrow (→)', () => {
      const updates = extract(MIXED_PR_BODY)
      const systemDep = updates.find(u => u.name === 'bun.com')
      expect(systemDep).toBeDefined()
      expect(systemDep!.currentVersion).toBe('1.3.1')
      expect(systemDep!.newVersion).toBe('1.3.4')
    })

    it('should extract BOTH npm and system deps from mixed PR body', () => {
      const updates = extract(MIXED_PR_BODY)
      expect(updates.length).toBe(2)

      const npmDep = updates.find(u => u.name === '@types/bun')
      expect(npmDep).toBeDefined()
      expect(npmDep!.currentVersion).toBe('1.3.10')
      expect(npmDep!.newVersion).toBe('1.3.11')

      const systemDep = updates.find(u => u.name === 'bun.com')
      expect(systemDep).toBeDefined()
      expect(systemDep!.currentVersion).toBe('1.3.1')
      expect(systemDep!.newVersion).toBe('1.3.4')
    })

    it('should extract GitHub Actions with Unicode arrow (→)', () => {
      const updates = extract(GITHUB_ACTIONS_PR_BODY)
      expect(updates.length).toBe(3)

      const setupBun = updates.find(u => u.name === 'oven-sh/setup-bun')
      expect(setupBun).toBeDefined()
      expect(setupBun!.currentVersion).toBe('2.1.2')
      expect(setupBun!.newVersion).toBe('2.2.0')

      const checkout = updates.find(u => u.name === 'actions/checkout')
      expect(checkout).toBeDefined()
      expect(checkout!.currentVersion).toBe('4.2.1')
      expect(checkout!.newVersion).toBe('4.2.2')
    })

    it('should strip version prefixes (^, ~, v) from extracted versions', () => {
      const updates = extract(MIXED_PR_BODY)
      // System dep `^1.3.1` should have prefix stripped
      const systemDep = updates.find(u => u.name === 'bun.com')
      expect(systemDep!.currentVersion).not.toContain('^')
      expect(systemDep!.newVersion).not.toContain('^')

      // GH Actions `v2.1.2` should have prefix stripped
      const ghUpdates = extract(GITHUB_ACTIONS_PR_BODY)
      const setupBun = ghUpdates.find(u => u.name === 'oven-sh/setup-bun')
      expect(setupBun!.currentVersion).not.toContain('v')
    })

    it('should deduplicate packages by name', () => {
      const bodyWithDuplicates = `
| [react](https://reactjs.org) | \`17.0.0\` -> \`18.0.0\` | badge |
| [react](https://reactjs.org) | \`17.0.0\` → \`18.0.0\` | badge |`
      const updates = extract(bodyWithDuplicates)
      expect(updates.length).toBe(1)
    })

    it('should return empty array for body with no tables', () => {
      const updates = extract('No package updates here, just text.')
      expect(updates.length).toBe(0)
    })
  })

  describe('checkIfUpdatesMatch (via Buddy)', () => {
    const buddy = createTestBuddy()
    const checkMatch = (body: string, updates: PackageUpdate[]) =>
      (buddy as any).checkIfUpdatesMatch(body, updates)

    it('should match when npm updates are identical', () => {
      const updates: PackageUpdate[] = [
        { name: 'typescript', currentVersion: '^5.8.2', newVersion: '^5.8.3', updateType: 'patch', file: 'package.json', dependencyType: 'dependencies' },
        { name: 'eslint', currentVersion: '^9.0.0', newVersion: '^9.1.0', updateType: 'minor', file: 'package.json', dependencyType: 'dependencies' },
      ]
      expect(checkMatch(NPM_ONLY_PR_BODY, updates)).toBe(true)
    })

    it('should NOT match when a version differs', () => {
      const updates: PackageUpdate[] = [
        { name: 'typescript', currentVersion: '^5.8.2', newVersion: '^5.8.4', updateType: 'patch', file: 'package.json', dependencyType: 'dependencies' },
        { name: 'eslint', currentVersion: '^9.0.0', newVersion: '^9.1.0', updateType: 'minor', file: 'package.json', dependencyType: 'dependencies' },
      ]
      expect(checkMatch(NPM_ONLY_PR_BODY, updates)).toBe(false)
    })

    it('should NOT match when update count differs (new package added)', () => {
      const updates: PackageUpdate[] = [
        { name: 'typescript', currentVersion: '^5.8.2', newVersion: '^5.8.3', updateType: 'patch', file: 'package.json', dependencyType: 'dependencies' },
      ]
      // PR body has 2 updates but we only have 1
      expect(checkMatch(NPM_ONLY_PR_BODY, updates)).toBe(false)
    })

    it('should match with version prefix normalization (^, v)', () => {
      // PR body has `1.3.10` -> `1.3.11` but update has `^1.3.11`
      const updates: PackageUpdate[] = [
        { name: '@types/bun', currentVersion: '^1.3.10', newVersion: '^1.3.11', updateType: 'patch', file: 'package.json', dependencyType: 'dependencies' },
        { name: 'bun.com', currentVersion: '^1.3.1', newVersion: '^1.3.4', updateType: 'patch', file: 'deps.yaml', dependencyType: 'dependencies' },
      ]
      expect(checkMatch(MIXED_PR_BODY, updates)).toBe(true)
    })

    it('should match GitHub Actions updates with v-prefix normalization', () => {
      const updates: PackageUpdate[] = [
        { name: 'oven-sh/setup-bun', currentVersion: 'v2.1.2', newVersion: 'v2.2.0', updateType: 'minor', file: '.github/workflows/ci.yml', dependencyType: 'github-actions' },
        { name: 'actions/checkout', currentVersion: 'v4.2.1', newVersion: 'v4.2.2', updateType: 'patch', file: '.github/workflows/ci.yml', dependencyType: 'github-actions' },
        { name: 'codecov/codecov-action', currentVersion: 'v4.5.0', newVersion: 'v5.0.0', updateType: 'major', file: '.github/workflows/ci.yml', dependencyType: 'github-actions' },
      ]
      expect(checkMatch(GITHUB_ACTIONS_PR_BODY, updates)).toBe(true)
    })

    it('should return false for empty body', () => {
      expect(checkMatch('', [])).toBe(false)
    })
  })

  describe('shouldAutoCloseForRespectLatest (false positive prevention)', () => {
    it('should NOT auto-close PR that mentions "main" only in config section', async () => {
      // This PR has normal semver versions but mentions "main" in the rebasing config section
      const result = await checkForAutoClose(
        { number: 100, body: MIXED_PR_BODY },
        { packages: { respectLatest: true } },
        mockLogger,
      )
      expect(result).toBe(false)
    })

    it('should NOT auto-close GitHub Actions PR that mentions "main"', async () => {
      const result = await checkForAutoClose(
        { number: 101, body: GITHUB_ACTIONS_PR_BODY },
        { packages: { respectLatest: true } },
        mockLogger,
      )
      expect(result).toBe(false)
    })

    it('should auto-close PR with actual dynamic version (*)', async () => {
      const prBody = `| Package | Change | Type |
|---|---|---|
| [python.org](https://pkgx.com/pkg/python.org) | \`*\` → \`3.13.5\` | 🔴 major |

This PR was generated by Buddy 🤖`
      const result = await checkForAutoClose(
        { number: 102, body: prBody },
        { packages: { respectLatest: true } },
        mockLogger,
      )
      expect(result).toBe(true)
    })

    it('should auto-close PR with actual dynamic version (latest)', async () => {
      const prBody = `| Package | Change | Type |
|---|---|---|
| [react](https://npmjs.com/package/react) | \`latest\` → \`18.2.0\` | 🔴 major |

This PR was generated by Buddy 🤖`
      const result = await checkForAutoClose(
        { number: 103, body: prBody },
        { packages: { respectLatest: true } },
        mockLogger,
      )
      expect(result).toBe(true)
    })

    it('should NOT auto-close when respectLatest is false', async () => {
      const prBody = `| [react](https://npmjs.com) | \`latest\` → \`18.2.0\` | 🔴 major |`
      const result = await checkForAutoClose(
        { number: 104, body: prBody },
        { packages: { respectLatest: false } },
        mockLogger,
      )
      expect(result).toBe(false)
    })
  })

  describe('Partial extraction safety', () => {
    const buddy = createTestBuddy()
    const extract = (body: string) => (buddy as any).extractPackageUpdatesFromPRBody(body)

    it('should extract ALL packages from mixed PR body (no partial extraction)', () => {
      const updates = extract(MIXED_PR_BODY)
      // PR declares 2 total — we must extract 2
      expect(updates.length).toBe(2)
    })

    it('should extract ALL packages from GitHub Actions PR body', () => {
      const updates = extract(GITHUB_ACTIONS_PR_BODY)
      // PR declares 3 total — we must extract 3
      expect(updates.length).toBe(3)
    })

    it('declared total should match extracted count for mixed body', () => {
      const totalMatch = MIXED_PR_BODY.match(/\*\*Total\*\*\s*\|\s*\*\*(\d+)\*\*/)
      const declaredTotal = totalMatch ? Number.parseInt(totalMatch[1], 10) : 0
      const updates = extract(MIXED_PR_BODY)
      expect(updates.length).toBe(declaredTotal)
    })

    it('declared total should match extracted count for GH Actions body', () => {
      const totalMatch = GITHUB_ACTIONS_PR_BODY.match(/\*\*Total\*\*\s*\|\s*\*\*(\d+)\*\*/)
      const declaredTotal = totalMatch ? Number.parseInt(totalMatch[1], 10) : 0
      const updates = extract(GITHUB_ACTIONS_PR_BODY)
      expect(updates.length).toBe(declaredTotal)
    })
  })

  describe('PR filter scope (buddy-bot only)', () => {
    function isBuddyBotPR(pr: Partial<PullRequest>): boolean {
      return pr.head?.startsWith('buddy-bot/') === true
        || (pr.author === 'github-actions[bot]' && (pr.labels?.includes('dependencies') ?? false))
    }

    it('should match buddy-bot PRs by branch name', () => {
      expect(isBuddyBotPR({ head: 'buddy-bot/update-non-major', author: 'chrisbbreuer', labels: [] })).toBe(true)
    })

    it('should match github-actions[bot] PRs with dependencies label', () => {
      expect(isBuddyBotPR({ head: 'buddy-bot/update-foo', author: 'github-actions[bot]', labels: ['dependencies'] })).toBe(true)
    })

    it('should NOT match Renovate PRs', () => {
      expect(isBuddyBotPR({ head: 'renovate/all-minor-patch', author: 'renovate[bot]', labels: ['dependencies'] })).toBe(false)
    })

    it('should NOT match Dependabot PRs', () => {
      expect(isBuddyBotPR({ head: 'dependabot/npm_and_yarn/react-18.0.0', author: 'dependabot[bot]', labels: ['dependencies'] })).toBe(false)
    })

    it('should NOT match random PRs with "update" in title', () => {
      expect(isBuddyBotPR({ head: 'feature/update-docs', author: 'developer', labels: [] })).toBe(false)
    })

    it('should NOT match human PRs with dependencies label', () => {
      expect(isBuddyBotPR({ head: 'chore/deps', author: 'developer', labels: ['dependencies'] })).toBe(false)
    })
  })

  describe('extractPackageNamesFromPRBody', () => {
    it('should extract package names from npm table', () => {
      const names = extractPackageNamesFromPRBody(NPM_ONLY_PR_BODY)
      expect(names).toContain('typescript')
      expect(names).toContain('eslint')
    })

    it('should extract package names from mixed body', () => {
      const names = extractPackageNamesFromPRBody(MIXED_PR_BODY)
      // The helper extracts from table format and release notes
      expect(names).toContain('bun.com')
    })
  })
})
