import type { Dependency, PackageFile } from '../types'
import { getDefaultLogger } from './logger'

/**
 * Interface for pantry.lock file structure
 */
export interface PantryLock {
  version: string
  packages: Record<string, PantryPackage>
}

/**
 * Interface for a single pantry package entry
 */
export interface PantryPackage {
  name: string
  version: string
  resolved: string
}

/**
 * Check if a file is a pantry.lock file
 *
 * Parsing is deliberately all this module does. `pantry.lock` is a lock file,
 * not a manifest: its contents follow from the dependency file beside it, so
 * it is regenerated by the install step in `lock-file.ts` rather than being
 * updated package by package. Parsing still earns its place — the dashboard
 * lists what a project actually resolved.
 */
export function isPantryLockFile(filePath: string): boolean {
  const fileName = filePath.split('/').pop() || ''
  return fileName === 'pantry.lock'
}

/**
 * Parse a pantry.lock file and extract dependencies
 */
export async function parsePantryLockFile(filePath: string, content: string): Promise<PackageFile | null> {
  try {
    const lockData: PantryLock = JSON.parse(content)
    const dependencies: Dependency[] = []

    if (lockData.packages) {
      for (const pkg of Object.values(lockData.packages)) {
        if (pkg.name && pkg.version) {
          dependencies.push({
            name: pkg.name,
            currentVersion: pkg.version,
            type: 'dependencies',
            file: filePath,
          })
        }
      }
    }

    return {
      path: filePath,
      type: 'pantry.lock',
      content,
      dependencies,
    }
  }
  catch (error) {
    getDefaultLogger().warn(`Failed to parse pantry.lock file ${filePath}:`, error)
    return null
  }
}
