name: Buddy Dependency Updates

on:
  schedule:
    # Patch updates daily at 2 AM
    - cron: '0 2 * * *'
    # Minor updates twice weekly at 2 AM (Monday, Thursday)
    - cron: '0 2 * * 1,4'
    # Major updates monthly at 2 AM (first of month)
    - cron: '0 2 1 * *'

  workflow_dispatch:
    inputs:
      strategy:
        description: Update strategy
        required: true
        default: all
        type: choice
        options:
          - all
          - major
          - minor
          - patch
      dry_run:
        description: Dry run (preview only)
        required: false
        default: false
        type: boolean
      packages:
        description: Specific packages (comma-separated)
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  determine-strategy:
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{ steps.strategy.outputs.strategy }}
      auto_merge: ${{ steps.strategy.outputs.auto_merge }}
    steps:
      - name: Determine update strategy
        id: strategy
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "strategy=${{ github.event.inputs.strategy }}" >> $GITHUB_OUTPUT
            echo "auto_merge=false" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.schedule }}" = "0 2 * * *" ]; then
            echo "strategy=patch" >> $GITHUB_OUTPUT
            echo "auto_merge=true" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.schedule }}" = "0 2 * * 1,4" ]; then
            echo "strategy=minor" >> $GITHUB_OUTPUT
            echo "auto_merge=false" >> $GITHUB_OUTPUT
          else
            echo "strategy=major" >> $GITHUB_OUTPUT
            echo "auto_merge=false" >> $GITHUB_OUTPUT
          fi

  dependency-updates:
    needs: determine-strategy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run Buddy dependency scan
        id: scan
        run: |
          STRATEGY="${{ needs.determine-strategy.outputs.strategy }}"

          if [ "${{ github.event.inputs.packages }}" != "" ]; then
            echo "Checking specific packages: ${{ github.event.inputs.packages }}"
            bunx @stacksjs/buddy scan --packages "${{ github.event.inputs.packages }}" --verbose
          else
            echo "Running $STRATEGY dependency scan..."
            bunx @stacksjs/buddy scan --strategy "$STRATEGY" --verbose
          fi

      - name: Update dependencies
        if: ${{ !github.event.inputs.dry_run }}
        run: |
          STRATEGY="${{ needs.determine-strategy.outputs.strategy }}"

          if [ "${{ github.event.inputs.packages }}" != "" ]; then
            bunx @stacksjs/buddy update --packages "${{ github.event.inputs.packages }}" --verbose
          else
            bunx @stacksjs/buddy update --strategy "$STRATEGY" --verbose
          fi

      - name: Auto-merge safe updates
        if: ${{ needs.determine-strategy.outputs.auto_merge == 'true' && !github.event.inputs.dry_run }}
        run: |
          echo "Auto-merging patch updates..."
          # Auto-merge logic for patch updates
          # This would be implemented when Git providers are fully integrated

      - name: Create summary
        if: always()
        run: |
          echo "## 🤖 Buddy Dependency Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Strategy**: ${{ needs.determine-strategy.outputs.strategy }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Auto-merge**: ${{ needs.determine-strategy.outputs.auto_merge }}" >> $GITHUB_STEP_SUMMARY

          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            echo "- **Mode**: Dry run (preview only)" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "View the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for detailed logs." >> $GITHUB_STEP_SUMMARY

  notify-on-failure:
    needs: [determine-strategy, dependency-updates]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Create issue on failure
        uses: actions/github-script@v7
        with:
          script: |
            const title = 'Buddy Dependency Update Failed';
            const body = `## 🚨 Dependency Update Failure

            The automated dependency update process failed.

            **Details:**
            - Strategy: ${{ needs.determine-strategy.outputs.strategy }}
            - Workflow: [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - Triggered by: ${{ github.event_name }}

            Please review the workflow logs and resolve any issues.
            `;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['bug', 'dependencies', 'automation']
            });
